# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.



[[main]]
  name = "首页"
  url = "#referral"
  weight = 10

[[main]]
  name = "文档"
  url = "documents"
  weight = 20
  identifier = "documents"

[[main]]
  name = "v2.x 文档"
  url = "documents/v2"
  weight = 21
  parent = "documents"

[[main]]
  name = "v1.x 文档"
  url = "documents/v1"
  weight = 22
  parent = "documents"

[[main]]
  name = "团队"
  url = "authors/"
  weight = 30

[[main]]
  name = "赞助"
  url = "donation/"
  weight = 40

[[main]]
  name = "多语言"
  weight = 50
  identifier = "translations"

[[main]]
  name = "English"
  weight = 51
  parent = "translations"

[[main]]
  name = "中文"
  weight = 52
  parent = "translations"


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

# v2文档一级菜单
[[v2]]
  name = "框架概述"
  weight = 1
  url = "/documents/v2/"
[[v2]]
  name = "开发指南"
  weight = 20
  identifier = "dev-guide"
[[v2]]
  name = "快速开始"
  weight = 30
  identifier = "quick-start"
[[v2]]
  name = "开发工具"
  weight = 40
  identifier = "dev-tools"
[[v2]]
  name = "基础组件"
  weight = 50
  identifier = "basic-components"

[[v2]]
  name = "核心组件"
  weight = 60
  identifier = "core-components"


[[v2]]
  name = "MYSQL"
  weight = 70
  identifier = "mysql"

[[v2]]
  name = "Redis"
  weight = 80
  identifier = "redis"

[[v2]]
  name = "扩展组件"
  weight = 90
  identifier = "ext-components"
[[v2]]
  name = "微服务"
  weight = 100
  identifier = "microservice"
  [[v2]]
  name = "贡献"
  weight = 110
  identifier = "contribute"
  [[v2]]
  name = "附录"
  weight = 120
  identifier = "appendix"